### ISSUE TITLE
trouble with sysmoUSIM-SJS1 4FF

### ISSUE THREAD

**Issue by EugeneBogush** [herlesupreeth/CoIMS_Wiki#1]
sim@machine:/opt/CoIMS_Wiki$ gp --key-enc KIC1 --key-mac KID1 --key-dek KIK1 -lvi
GlobalPlatformPro 19.06.16-8-g9639eb9
Running on Linux 5.3.0-26-generic amd64, Java 11.0.6 by Ubuntu
Reader: OMNIKEY AG CardMan 3121 00 00
ATR: 3B9F96801FC78031A073BE21136743200718000001A5
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B9F96801FC78031A073BE21136743200718000001A5

[DEBUG] GPSession - Auto-detected ISD: A000000003000000
[WARN] GPData - Invalid CPLC date: FFFF
[WARN] GPData - Invalid CPLC date: FFFF
[WARN] GPData - Invalid CPLC date: FFFF
[WARN] GPData - Invalid CPLC date: FFFF
[WARN] GPData - Invalid CPLC date: FFFF
[WARN] GPData - Invalid CPLC date: FFFF
CPLC: ICFabricator=FFFF
      ICType=FFFF
      OperatingSystemID=FFFF
      OperatingSystemReleaseDate=FFFF (invalid date format)
      OperatingSystemReleaseLevel=FFFF
      ICFabricationDate=FFFF (invalid date format)
      ICSerialNumber=FFFFFFFF
      ICBatchIdentifier=FFFF
      ICModuleFabricator=FFFF
      ICModulePackagingDate=FFFF (invalid date format)
      ICCManufacturer=FFFF
      ICEmbeddingDate=FFFF (invalid date format)
      ICPrePersonalizer=FFFF
      ICPrePersonalizationEquipmentDate=FFFF (invalid date format)
      ICPrePersonalizationEquipmentID=FFFFFFFF
      ICPersonalizer=FFFF
      ICPersonalizationDate=FFFF (invalid date format)
      ICPersonalizationEquipmentID=FFFFFFFF

IIN: 42020102
CIN: 45020506
Card Data: 
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.1.1
-> GP Version: 2.1.1
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.2.21
-> GP SCP02 i=15
Card Capabilities: 
[DEBUG] GPData - GET DATA(Card Capabilities): N/A
Version:   1 (0x01) ID:   1 (0x01) type: DES3 length:  16 
Version:   1 (0x01) ID:   2 (0x02) type: DES3 length:  16 
Version:   1 (0x01) ID:   3 (0x03) type: DES3 length:  16 
Version:   2 (0x02) ID:   1 (0x01) type: DES3 length:  16 
Version:   2 (0x02) ID:   2 (0x02) type: DES3 length:  16 
Version:   2 (0x02) ID:   3 (0x03) type: DES3 length:  16 
Version:   3 (0x03) ID:   1 (0x01) type: DES3 length:  16 
Version:   3 (0x03) ID:   2 (0x02) type: DES3 length:  16 
Version:   3 (0x03) ID:   3 (0x03) type: DES3 length:  16 
Exception in thread "main" java.lang.IllegalArgumentException: Illegal hex: K
    at apdu4j.HexUtils.decodeHexString_imp(HexUtils.java:58)
    at apdu4j.HexUtils.stringToBin(HexUtils.java:83)
    at pro.javacard.gp.GPTool.main(GPTool.java:278)

**Comment by herlesupreeth** [comment]
You should replace KIC1, KID1 and KIK1 with the values sent to you by sysmocom (the email containing values of adm keys, imsi, ki, kic, kid, kik etc.)

**Comment by EugeneBogush** [comment]
sorry, my mistake!
