### ISSUE TITLE
SW match failed!

### ISSUE THREAD

**Issue by rezo552** [herlesupreeth/CoIMS_Wiki#10]
I just got some brand new ISIM from Sysmocom but Im failing to install the applet (neither gp or shadysim works). Does anyone have any idea?

(env) rezo@rezo-Latitude-E5540:~/.virtualenvs/sim-tools/shadysim$ python shadysim_isim.py --pcsc -t --kic A5CEF1129E33A42D1535ED10F4155B23 --kid 6870D292A589EDD1E8F58127E8DC047F
AID: a0000000620001, State: 01, Privs: 00
AID: 4a6176656c696e2e6a637265, State: 01, Privs: 00
AID: a0000000620101, State: 01, Privs: 00
AID: a0000000620102, State: 01, Privs: 00
AID: a0000000620201, State: 01, Privs: 00
AID: a000000062020801, State: 01, Privs: 00
AID: a00000006202080101, State: 01, Privs: 00
AID: a0000000620002, State: 01, Privs: 00
AID: a0000000620003, State: 01, Privs: 00
AID: a000000062010101, State: 01, Privs: 00
AID: a00000015100, State: 01, Privs: 00
AID: a0000000090005ffffffff8911000000, State: 01, Privs: 00
AID: a0000000090005ffffffff8912000000, State: 01, Privs: 00
AID: a0000000090005ffffffff8913000000, State: 01, Privs: 00
AID: a0000000090005ffffffff8911010000, State: 01, Privs: 00
AID: a0000000871005ffffffff8913100000, State: 01, Privs: 00
AID: a0000000871005ffffffff8913200000, State: 01, Privs: 00
AID: a0000000090003ffffffff8910710001, State: 01, Privs: 00
AID: a0000000090003ffffffff8910710002, State: 01, Privs: 00
AID: a0000000090005ffffffff8915000000, State: 01, Privs: 00
AID: a00000015141434c, State: 01, Privs: 00
    Instance AID: a00000015141434c00

python shadysim_isim.py --pcsc -l applet.cap -i applet.cap --kic A5CEF1129E33A42D1535ED10F4155B23 --kid 6870D292A589EDD1E8F58127E8DC047F --module-aid a00000015141434c00 --instance-aid a00000015141434c00
Traceback (most recent call last):
  File "shadysim_isim.py", line 494, in <module>
    ac.load_app(args.load_app)
  File "shadysim_isim.py", line 369, in load_app
    self.load_aid_raw(aid, data, len(data) / 2)
  File "shadysim_isim.py", line 271, in load_aid_raw
    self.send_wrapped_apdu_checksw('80e60200' + ('%02x' % (len(data) / 2)) + data + '00c0000000')
  File "shadysim_isim.py", line 246, in send_wrapped_apdu_checksw
    raise RuntimeError("SW match failed! Expected %s and got %s." % (sw.lower(), response[1]))
RuntimeError: SW match failed! Expected 9000 and got 6985.

**Comment by herlesupreeth** [comment]
If you have the new ISIMs from Sysmocom then no need to install the applet, its already installed. You just need to push the certificate

> AID: a00000015141434c, State: 01, Privs: 00
> Instance AID: a00000015141434c00
> 

The above logs is the proof that its already installed

**Comment by rezo552** [comment]
Thanks, now its almost working... The IMS registration fails at the very end for some reason:

ims_registrar_scscf [lookup.c:284]: impu_registered(): Looking for IMPU <sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org>
scscf        |  2(37) DEBUG: ims_registrar_scscf [lookup.c:303]: impu_registered(): 'sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org' not found in usrloc
scscf        |  2(37) ERROR: <script>: Not REGISTERED
scscf        |  2(37) DEBUG: ims_registrar_scscf [save.c:1269]: save(): Looking for route block [PRE_REG_SAR_REPLY]
scscf        |  2(37) DEBUG: ims_registrar_scscf [save.c:1326]: save(): preparing for SAR assignment for new REGISTRATION <sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org>
scscf        |  2(37) INFO: ims_registrar_scscf [cxdx_sar.c:84]: create_return_code(): created AVP successfully : [saa_return_code] - [-2]
scscf        |  2(37) DEBUG: ims_registrar_scscf [save.c:1430]: save(): Suspending SIP TM transaction with index [0] and label [0]
fhoss        | [Thread-17] INFO  de.fhg.fokus.hss.cx.op.SAR  - 
fhoss        | 
fhoss        | The UserData XML document which is sent to the S-CSCF:
fhoss        | <?xml version="1.0" encoding="UTF-8"?><IMSSubscription><PrivateID>06701234567@ims.mnc070.mcc999.3gppnetwork.org</PrivateID><ServiceProfile><PublicIdentity><Identity>sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org </Identity><Extension><IdentityType>0</IdentityType></Extension></PublicIdentity><InitialFilterCriteria><Priority>0</Priority><TriggerPoint><ConditionTypeCNF>0</ConditionTypeCNF><SPT><ConditionNegated>0</ConditionNegated><Group>0</Group><Method>PUBLISH</Method><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>0</Group><SIPHeader><Header>Event</Header><Content>.*presence.*</Content></SIPHeader><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>0</Group><SessionCase>0</SessionCase><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>1</Group><Method>PUBLISH</Method><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>1</Group><SIPHeader><Header>Event</Header><Content>.*presence.*</Content></SIPHeader><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>1</Group><SessionCase>3</SessionCase><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>2</Group><Method>SUBSCRIBE</Method><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>2</Group><SIPHeader><Header>Event</Header><Content>.*presence.*</Content></SIPHeader><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>2</Group><SessionCase>1</SessionCase><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>3</Group><Method>SUBSCRIBE</Method><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>3</Group><SIPHeader><Header>Event</Header><Content>.*presence.*</Content></SIPHeader><Extension></Extension></SPT><SPT><ConditionNegated>0</ConditionNegated><Group>3</Group><SessionCase>2</SessionCase><Extension></Extension></SPT></TriggerPoint><ApplicationServer><ServerName>sip:127.0.0.1:5065</ServerName><DefaultHandling>0</DefaultHandling></ApplicationServer></InitialFilterCriteria></ServiceProfile></IMSSubscription>
fhoss        | [Thread-17] INFO  de.fhg.fokus.hss.cx.op.SAR  - 
fhoss        | User with Public Identity: sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org  and all its coresponding implicit-set identities are Registered!
scscf        |  9(44) DEBUG: ims_registrar_scscf [cxdx_sar.c:142]: async_cdp_callback(): There is transaction data this must have been called from save or assign server unreg 9(44) DEBUG: ims_registrar_scscf [cxdx_sar.c:189]: async_cdp_callback(): callid for found transaction is [2637349364_3930611484@192.168.101.2]
scscf        |  9(44) INFO: ims_registrar_scscf [cxdx_avp.c:138]: cxdx_get_avp(): cxdx_get_experimental_result_code: Failed finding avp
scscf        |  9(44) DEBUG: ims_registrar_scscf [cxdx_sar.c:214]: async_cdp_callback(): received AAA success for SAR - SAA
scscf        |  9(44) DEBUG: ims_registrar_scscf [cxdx_sar.c:233]: async_cdp_callback(): Parsing user data string from SAA
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:760]: parse_service_profile(): child name is [PublicIdentity]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:760]: parse_service_profile(): child name is [InitialFilterCriteria]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1016]: print_user_data(): IMSSubscription:
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1019]: print_user_data(): Private Identity: <06701234567@ims.mnc070.mcc999.3gppnetwork.org>
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1021]: print_user_data(): 	Service Profile:
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1023]: print_user_data(): 		Public Identity: Barring [0] <sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org > 
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1029]: print_user_data(): 		Filter Criteria: Priority [0]ProfilePartInd [-1]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1034]: print_user_data(): 			Trigger Point: CNF [ ] (_&_)|(_&_)
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[0] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1051]: print_user_data(): 					 Method == <PUBLISH>
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[0] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1056]: print_user_data(): 					 Hdr(Event(22)) == <.*presence.*>
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[0] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1064]: print_user_data(): 					 SessionCase [0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[1] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1051]: print_user_data(): 					 Method == <PUBLISH>
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[1] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1056]: print_user_data(): 					 Hdr(Event(22)) == <.*presence.*>
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[1] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1064]: print_user_data(): 					 SessionCase [3]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[2] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1051]: print_user_data(): 					 Method == <SUBSCRIBE>
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[2] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1056]: print_user_data(): 					 Hdr(Event(22)) == <.*presence.*>
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[2] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1064]: print_user_data(): 					 SessionCase [1]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[3] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1051]: print_user_data(): 					 Method == <SUBSCRIBE>
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[3] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1056]: print_user_data(): 					 Hdr(Event(22)) == <.*presence.*>
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1039]: print_user_data(): 				SPT: Grp[3] NOT[ ] RegType[0]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1064]: print_user_data(): 					 SessionCase [2]
scscf        |  9(44) DEBUG: ims_registrar_scscf [userdata_parser.c:1077]: print_user_data(): 			AS: <sip:127.0.0.1:5065> Handling [0] SrvInfo: <>
scscf        |  9(44) DEBUG: ims_registrar_scscf [cxdx_sar.c:240]: async_cdp_callback(): Successfully parse user data XML setting ref to 1 (we are referencing it)
scscf        |  9(44) DEBUG: ims_registrar_scscf [save.c:790]: update_contacts(): updating contacts in REGISTRATION state
scscf        |  9(44) DEBUG: ims_usrloc_scscf [udomain.c:792]: get_subscription(): found an existing subscription for IMPI [06701234567@ims.mnc070.mcc999.3gppnetwork.org]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:1274]: ref_subscription_unsafe(): Reffing subscription [06701234567@ims.mnc070.mcc999.3gppnetwork.org] - was [2]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:878]: compare_subscription(): Comparing subscription for IMPI [06701234567@ims.mnc070.mcc999.3gppnetwork.org]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:883]: compare_subscription(): new sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org  (50) vs. orig sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org  (50)
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:1004]: update_impurecord(): updating IMPU record with public identity for <sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org >
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:1036]: update_impurecord(): IMS subscription passed into update_impurecord
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:1043]: update_impurecord(): new subscription is the same as the old one....not doing anything 9(44) DEBUG: ims_usrloc_scscf [impurecord.c:1285]: unref_subscription_unsafe(): un-reffing subscription [06701234567@ims.mnc070.mcc999.3gppnetwork.org] - was [3]
scscf        |  9(44) DEBUG: ims_registrar_scscf [save.c:519]: update_contacts_helper(): updating the contacts for IMPU <sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org >
scscf        |  9(44) DEBUG: ims_registrar_scscf [save.c:137]: calc_contact_expires(): Calculated expires for contact is 600000
scscf        |  9(44) DEBUG: ims_registrar_scscf [save.c:545]: update_contacts_helper(): Need to update contact: <sip:c4dad9d1-eea7-48f6-af18-7795ae4ec9c1@192.168.101.2:40195;alias=192.168.101.2~44538~2>: q_value [-1],sos: [0],expires [600000]
scscf        |  9(44) DEBUG: ims_registrar_scscf [save.c:550]: update_contacts_helper(): packing contact information
scscf        |  9(44) DEBUG: ims_registrar_scscf [save.c:556]: update_contacts_helper(): adding/updating contact based on prior existence
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:748]: get_scontact(): looking for contact [sip:c4dad9d1-eea7-48f6-af18-7795ae4ec9c1@192.168.101.2:40195;alias=192.168.101.2~44538~2] in slot 238
scscf        |  9(44) DEBUG: ims_registrar_scscf [save.c:562]: update_contacts_helper(): inserting new contact
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:533]: insert_scontact(): Too many contacts already registered, overwriting oldest for IMPU <sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org >
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:551]: insert_scontact(): Too many 3GPP contacts already registered, overwriting oldest for IMPU <sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org >
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:562]: insert_scontact(): INSERTing ucontact in usrloc module
scscf        |  9(44) DEBUG: ims_usrloc_scscf [ucontact.c:118]: new_ucontact(): Checking param [+g.3gpp.accesstype]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [ucontact.c:118]: new_ucontact(): Checking param [+sip.instance]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [ucontact.c:118]: new_ucontact(): Checking param [video]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [ucontact.c:118]: new_ucontact(): Checking param [audio]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [ucontact.c:118]: new_ucontact(): Checking param [+g.3gpp.smsip]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [ucontact.c:118]: new_ucontact(): Checking param [+g.3gpp.nw-init-ussi]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [ucontact.c:118]: new_ucontact(): Checking param [+g.3gpp.icsi-ref]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [ucontact.c:173]: new_ucontact(): generating hash based on [sip:c4dad9d1-eea7-48f6-af18-7795ae4ec9c1@192.168.101.2:40195;alias=192.168.101.2~44538~2]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:280]: mem_insert_scontact(): Created new contact in memory with AOR: [sip:c4dad9d1-eea7-48f6-af18-7795ae4ec9c1@192.168.101.2:40195;alias=192.168.101.2~44538~2] and hash [238]
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:1140]: link_contact_to_impu(): Need to overwrite oldest (first) 3GPP contact
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:1145]: link_contact_to_impu(): Found first 3GPP contact 9(44) DEBUG: ims_usrloc_scscf [udomain.c:852]: unref_contact_unsafe(): decrementing ref count on contact [sip:42d2bbec-6d6d-4ef4-a156-c79b0c7fe7b7@192.168.101.2:42891;alias=192.168.101.2~43539~2], was 1
scscf        |  9(44) DEBUG: ims_usrloc_scscf [udomain.c:855]: unref_contact_unsafe(): contact [sip:42d2bbec-6d6d-4ef4-a156-c79b0c7fe7b7@192.168.101.2:42891;alias=192.168.101.2~43539~2] no longer referenced.... deleting
scscf        |  9(44) DEBUG: ims_usrloc_scscf [udomain.c:843]: ref_contact_unsafe(): incrementing ref count on contact [sip:c4dad9d1-eea7-48f6-af18-7795ae4ec9c1@192.168.101.2:40195;alias=192.168.101.2~44538~2], was 1
scscf        |  9(44) DEBUG: ims_usrloc_scscf [impurecord.c:1226]: link_contact_to_impu(): number of contacts for IMPU [sip:06701234567@ims.mnc070.mcc999.3gppnetwork.org ] is 5
scscf        |  9(44) DEBUG: ims_usrloc_scscf [udomain.c:852]: unref_contact_unsafe(): decrementing ref count on contact [sip:c4dad9d1-eea7-48f6-af18-7795ae4ec9c1@192.168.101.2:40195;alias=192.168.101.2~44538~2], was 2
scscf        |  9(44) DEBUG: ims_usrloc_scscf [ul_callback.h:119]: run_ul_callbacks(): impurecord=0x7f93a5d64f30, contact=0x7f93a5d786f0, callback type 1024/1024, id 0 entered
scscf        |  9(44) DEBUG: ims_registrar_scscf [usrloc_cb.c:88]: ul_contact_changed(): Received notification of type 1024 on contact Address <sip:c4dad9d1-eea7-48f6-af18-7795ae4ec9c1@192.168.101.2:40195;alias=192.168.101.2~44538~2>
scscf        |  9(44) DEBUG: ims_registrar_scscf [usrloc_cb.c:91]: ul_contact_changed(): There are no subscriptions for this IMPU therefore breaking out now as nothing to do
scscf        |  9(44) ERROR: ims_registrar_scscf [save.c:826]: update_contacts(): Error, we should have a record after registraion
scscf        |  9(44) ERROR: ims_registrar_scscf [cxdx_sar.c:253]: async_cdp_callback(): Error processing REGISTER

**Comment by herlesupreeth** [comment]
please open ims related issue in relevant repo. Also mentioned which HSS you are using for IMS

**Comment by rezo552** [comment]
only the cert should have been uploaded
