### ISSUE TITLE
Getting SIM Carrier id = -1 in CoIMS app

### ISSUE THREAD

**Issue by mmarquez999** [herlesupreeth/CoIMS_Wiki#11]
Hi @herlesupreeth,

I've been trying the **VoLTE Setup with Kamailio IMS and Open5GS** (https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/) but I'm struggling with the configuration of my UE. I'm using a Huawei Mate 20X (Android 10) with a single SIM slot and a **sysmoISIM-SJA2**. 

I got the CoIMS app working by following your instructions but the **SIM Carrier Id** is set to -1 and I don't know how to fix it. I checked the section **Potential reasons for this method not working** and the PLMN that I'm using (99970) is not in the lists provided. But I don't know how to proceed with the alternative link you provided (https://source.android.com/devices/tech/config/carrierid#integrating_carrier_ids_with_carrierconfig).

Also, I'm **not able to configure the APN ims** in the phone: as soon as I set the APN type to 'ims' and save, it takes me back to the APN settings screen but without adding this new APN. I only have the APN internet available to select.

Are these two things related? I would really appreciate your help!

Thank you in advance.

**Comment by herlesupreeth** [comment]
I would suggest to change the PLMN of your network + sim to 001 01 rather than 999 70

**Comment by mmarquez999** [comment]
That seems to have been the solution: now using mcc/mnc 001 01 is working fine.

Thank you!
