### ISSUE TITLE
Is there a way to get a pre-programmed SIM card?

### ISSUE THREAD

**Issue by h44z** [herlesupreeth/CoIMS_Wiki#12]
Hi,

I want to use CoIMS to enable VoLTE on my Pixel 7 phone (for Austrian carriers) but I don't have writable SIM cards nor a SIM programmer.
Would it be possible to buy a pre-programmed SIM card somehow?

**Comment by herlesupreeth** [comment]
Not sure. But IMO you would need a SIM programmer and certain SIM related keys to push the SHA1 certificate atleast

**Comment by h44z** [comment]
All I need is just a SIM where the SHA1 certificate is already programmed. To avoid buying a programmer I was wondering if someone offers a "flashing/programming" service.

**Comment by herlesupreeth** [comment]
Ah I see. If you were in Germany I would have helped (need to also check the availability of SIM cards at Sysmocom). If not, let see other community member may help.

**Comment by h44z** [comment]
I live in Austria, does that count? The shop lists sim cards, but only 10 packs.  Do you know if it is possible to buy single sims?

**Comment by herlesupreeth** [comment]
I remember seeing listing on Amazon.com (US Website) and they provided only one SIM card and it was expensive.

If you can cover the postal charges, I should have a spare SIM card which I could send you. We can talk via email for coordination (in my github profile).
