### ISSUE TITLE
how can use this instruction for other simcards?

### ISSUE THREAD

**Issue by faratell** [herlesupreeth/CoIMS_Wiki#15]
Hello.
I have installed open5gs and Kamilio according to the instruction in https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/.
I use OYeITimes simcards that support volte and set volte parameters domain, i.e. IMPI, IMPU and pcscf as follow picture. 
![image](https://github.com/user-attachments/assets/e98ca2f6-1d53-4f69-a4da-e78462cc8d2a)

This simcard have correctly connect to internet in my developed open5gs-kamilio core and srsenb+b210  RAN.
I use samsung s24 mobile phone which supported volte (It was tested with other commercial simcards).
when i create ims apn and set type ims, it was not maintained in ims type and change to default after save apn. Volte is not enabled for my sim in the phone. 
 should I follow your instruction to enable volte for my simcard, although the volte is enabled in that for other commercial simcard?  I have not any kik, kid, kic , and not able to set in my simcard program software. 
![image](https://github.com/user-attachments/assets/12c042e1-149a-42b7-98ca-3d1ddc8bc1a3)
what should i do??

**Comment by herlesupreeth** [comment]
I dont think its possible if you dont have kik, kid, kic. As far as I know the SIM cards from OYeITimes dont allow programming those fields from that software.

> should I follow your instruction to enable volte for my simcard, although the volte is enabled in that for other commercial simcard?

That's because Samsung has enabled (at OS level) VoLTE only for that operator PLMN or any SIM specific identifier.

**Comment by faratell** [comment]
Thanks.
I found that is able to set kik.kid and kic in oyeitimes sims when write it. what should be set for these valuses? can be desirable random values?

**Comment by herlesupreeth** [comment]
Thats great news. yeah, it can be any value. For simplicity I would suggest writing the following values for kik, kid, and kic
`404142434445464748494A4B4C4D4E4F`

**Comment by faratell** [comment]
thanks for your reply.
I have simcard reader but oyeitimes programmer software only work on windows. When i program my sim with kic,kid and kik , i should follow all steps that you provieded or jump to step 4?

**Comment by faratell** [comment]
thanks for your reply.
I have simcard reader but oyeitimes programmer software only work on windows. When i program my sim with kic,kid and kik , i should follow all steps that you provieded or jump to step 4?

**Comment by herlesupreeth** [comment]
> When i program my sim with kic,kid and kik , i should follow all steps that you provieded or jump to step 4?

you could start from step 3 but dont forget to provide kik, kid and kic while installing applet + pushing certificate

**Comment by faratell** [comment]
I use ubuntu 22.04 but my simcard reader not work in it and only work on windows.
It seems I can not unlock it.
gp --key-enc 404142434445464748494A4B4C4D4E4F --key-mac 404142434445464748494A4B4C4D4E4F --key-dek 404142434445464748494A4B4C4D4E4F --install applet.ca
### Usage: gp [options] [GP files]
Available options:
  [-f,--fast]		Fast start: do not read .gprc
  [-q,--quiet]		Quiet mode: do not print banner and history numbers
  [-s stacksize]	Start with the PARI stack of given size (in bytes)
  [--default key=val]	Execute default(key,val) on startup
  [--emacs]		Run as if in Emacs shell
  [--help]		Print this message
  [--test]		Test mode. No history, wrap long lines (bench only)
  [--texmacs]		Run as if using TeXmacs frontend
  [--version]		Output version info and exit
  [--version-short]	Output version number and exit

What's your idea about the method described in these links with shizuku and Pixel IMS?
https://xdaforums.com/t/guide-enable-volte-without-rooting-or-unlocking-shizuku-pixel-volte-patch.4672809/
https://github.com/kyujin-cho/pixel-volte-patch/blob/main/README.en.md

**Comment by herlesupreeth** [comment]
> What's your idea about the method described in these links with shizuku and Pixel IMS?

I remember someone trying it out and saying it worked

**Comment by faratell** [comment]
I set mcc=999 and mnc=55. With that configuration to enable volte with shizuku and pixel IMS is it ok or must change plmn to 00101?

**Comment by herlesupreeth** [comment]
As far as I remeber the shizuku method didnt depend on MNC and MCC

**Comment by faratell** [comment]
Thanks herlesupreeth for your response. I will feedback the results here.

**Comment by faratell** [comment]
I used the Pixel IMS and Shizuku apps. These apps work well for my phone (Nokia 3.2) to enable VoLTE for the Iranian operator Irancell (MCC=432 and MNC=35). However, when I tried to enable VoLTE for a  open5gs network, it did not work.
I haved tried it for MCC=001 and MNC=01 and also MCC=999 and MNC=55.
Have you any idea to how i can enable volte on my simcards?

**Comment by herlesupreeth** [comment]
sorry, I cant be of much help here. VoLTE cant be activated just from SIM cards thats the sad part. If you are using any other phone apart from Samsung you would have better luck having VoLTE working

**Comment by faratell** [comment]
Thanks.
Which brand for phones is better to enable my private VolTE? Would it help to add my plmn specifics to carrier_list database (https://source.android.com/docs/core/connect/carrierid#integrating_carrier_ids_with_carrierconfig)
?

**Comment by herlesupreeth** [comment]
> Which brand for phones is better to enable my private VolTE? 

Usually Pixel phones, OnePlus phone. In general phones containing Qualcomm Baseband Modem (Except Samsung devices)

> Would it help to add my plmn specifics to carrier_list database 

i dont think it will help in case of Samsung device. As they maintain the settings to apply in an XML at unknown location

**Comment by faratell** [comment]
Thanks.
Is it true that only on these phones can we enable Open5GS VoLTE for private networks? 
Is it true that with PLMN=00101 we should enable VoLTE for Samsung phones? 
I tried to change the PLMN by only modifying the MCC and MNC in the mme.conf and enb.yaml files, without changing the domain address (ims.mnc55.mcc999.FarazNET.org). Is that important?

**Comment by herlesupreeth** [comment]
> Is it true that only on these phones can we enable Open5GS VoLTE for private networks?

First, the trend I see in most phones is that IMS is not enabled when using network with private network PLMN

> Is it true that with PLMN=00101 we should enable VoLTE for Samsung phones?

yes, as per my observation. Whereas on iPhones X and above its enabled by default

> I tried to change the PLMN by only modifying the MCC and MNC in the mme.conf and enb.yaml files, without changing the domain address (ims.mnc55.mcc999.FarazNET.org). Is that important?

I am not sure which domain address you are referring to here. Is it on the SIM or the IMS/DNS??

**Comment by faratell** [comment]
Thanks for your reply.
Domain address define DNS and also use for IMPI and IMPU , i.e: mnc001.mcc001.3gppnetwork.org
I Define this domain for my network as mnc55.mcc999.FarazNET.org. when i change mcc and mnc shoulde we change this domain (as mnc01.mcc001.FarazNET.org)?

**Comment by herlesupreeth** [comment]
> mnc001.mcc001.3gppnetwork.org

This is the 3GPP format defined when IMS domain is not configured in the SIM or ISIM is not present. So technically, you can have any arbitrary domain e.g. FarazNET.org without having any MNC or MCC. But as I said earlier, its upto the UE implementation to decide whether its gonna use the domain defined in the SIM or not

**Comment by faratell** [comment]
I use an iPhone 13, but I cannot find where to set the MCC and MNC in the settings.
![218893052188930506125417](https://github.com/user-attachments/assets/61c9eba5-d5ba-4c0f-ac62-803aa079ef5b)

**Comment by faratell** [comment]
I use an iPhone 13, but I cannot find where to set the MCC and MNC in the settings.
and only one apn can define in there. have you any information about iphone?
![photo13535643902(1)](https://github.com/user-attachments/assets/ab925da9-e6c9-4954-86e1-a3632647e1b1)

**Comment by faratell** [comment]
I use an iPhone 13. VoLTE is enabled, but I don't see the Access Point Name (APN) for voice that defines IMS.
I see that also my simcard is connected correctly in iphone but have not open any internet page.
mme        | 09/09 08:24:54.778: [mme] INFO: InitialUEMessage (../src/mme/s1ap-handler.c:426)
mme        | 09/09 08:24:54.778: [mme] INFO: [Added] Number of eNB-UEs is now 1 (../src/mme/mme-context.c:4800)
mme        | 09/09 08:24:54.778: [mme] INFO:     S_TMSI[G:2,C:1,M_TMSI:0xc00006d6] IMSI:[001010000000013] (../src/mme/s1ap-handler.c:508)
mme        | 09/09 08:24:54.778: [mme] INFO:     ENB_UE_S1AP_ID[13] MME_UE_S1AP_ID[13] TAC[1] CellID[0x19b01] (../src/mme/s1ap-handler.c:603)
mme        | 09/09 08:24:54.778: [emm] INFO: [001010000000013] Service request (../src/mme/emm-sm.c:317)
mme        | 09/09 08:24:54.778: [emm] INFO:     GUTI[G:2,C:1,M_TMSI:0xc00006d6] IMSI[001010000000013] (../src/mme/emm-handler.c:542)
mme        | 09/09 08:24:55.527: [mme] WARNING: APN duplicated [ims] (../src/mme/mme-context.c:4444)
mme        | 09/09 08:24:55.566: [emm] INFO: [001010000000013] Tracking area update request (../src/mme/emm-sm.c:497)
mme        | 09/09 08:24:55.566: [emm] INFO:     GUTI[G:2,C:1,M_TMSI:0xc00006d6] IMSI:[001010000000013] (../src/mme/emm-handler.c:718)

in enb :
Enter t to stop trace.
RACH:  tti=6381, cc=0, pci=1, preamble=28, offset=0, temp_crnti=0x46

               -----------------DL----------------|-------------------------UL-------------------------
rat  pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  pucch  phr  mcs  brate   ok  nok  (%)    bsr
lte    1   46   15   0    6   4.7k    3    0   0% |  11.3    9.3   37    1    18k    5    0   0%    0.0
User 0x46 connected
lte    1   46   15   0    5   3.1k   13    0   0% |   8.1    8.4   37    5    14k    7    0   0%    0.0
lte    1   46   15   0    0      0    0    0   0% |   8.2    7.9   37    7   2.5k    1    0   0%    0.0
User 0x46 connected
lte    1   46   15   0    6   1.4k    3    0   0% |   7.6    6.9   37    5   3.9k    2    0   0%    0.0
lte    1   46   15   0    1     56    1    0   0% |   7.2    8.6   38    4   1.4k    1    0   0%    0.0
lte    1   46   15   0    1     56    1    0   0% |   8.2   11.6   37    6    11k    5    0   0%    0.0
lte    1   46   15   0    1    344    5    0   0% |   8.1   11.3   37    6    35k   15    0   0%    0.0
User 0x46 connected
lte    1   46   15   0    3    576    5    0   0% |   8.3   10.8   36    5    31k   18    0   0%    0.0
lte    1   46  n/a   0    0      0    0    0   0% |   n/a    n/a    0    0      0    0    0   0%    0.0
lte    1   46  n/a   0    0      0    0    0   0% |   n/a    n/a    0    0      0    0    0   0%    0.0
lte    1   46   11   0    0      0    0    0   0% |   n/a    1.6    0    0      0    0    0   0%    0.0
User 0x46 connected

![photo13535643902(1)](https://github.com/user-attachments/assets/6fcb151a-8b80-4e49-8e2e-4fb49891fee6)
![photo13536094240](https://github.com/user-attachments/assets/82d1d49f-dd6d-4df6-b4ce-7d41f5af9d54)

**Comment by herlesupreeth** [comment]
This is deviating from the issue related to this repo. Please open in the respective repository. Also, post a pcap when you open an issue. The pcap should contain the traces taken when you attach the UE to the network

**Comment by faratell** [comment]
"Thank you. I created a new discussion at https://github.com/open5gs/open5gs/discussions/3458. Please pay attention."
