### ISSUE TITLE
How to verify if a USIM is programmable or not?

### ISSUE THREAD

**Issue by alishir** [herlesupreeth/CoIMS_Wiki#2]
Thanks for your great document. We have a USIM and a SIM programmer, how we can verify that our USIM is programmable or not?

**Comment by herlesupreeth** [comment]
Well, when you buy the SIM if the SIM card manufacturer provides information such as KIC1, KID1 and KIK1 per SIM card then you can be sure its a customizable SIM

Atleast, the above mentioned parameters are required in order to make use of the instructions mentioned in the Wiki

**Comment by alishir** [comment]
Thanks a lot for your guidance.
