### ISSUE TITLE
Android 8

### ISSUE THREAD

**Issue by miaoski** [herlesupreeth/CoIMS_Wiki#5]
Hi.
Is it possible to support Android 8?  Asus Zenfone 3 (ZE520KL) supports VoLTE, but its latest OS is Oreo.

Thank you!

**Comment by herlesupreeth** [comment]
As per Google Android Source, it should be possible to have Carrier Privileges working from Android 7.1 onwards. But from Android 9 onwards there is a different implementation of IMS Service and I am not sure how compatible it is with Carrier Configuration changes. I had tried to support more devices by extending this implementation to Android 8 atleast but was not possible due to method and libraries not compatible with older Android version.

**Comment by miaoski** [comment]
Pity that I'm not familiar with Android programming.  Zenfone 3 (ZE520KL) supports VoLTE in various carriers, including three carriers in where I live.  It would be nice if I can test non-ipsec IMS call on it.

**Comment by herlesupreeth** [comment]
There is some good news. I managed to support Android 8.0 and above devices. Please try it out on Android 8.0 device. I dont have any Android 8.0 device to test. Please let me know how it goes.

Btw, you wont see Carrier ID in Android 8.0 device as the API doesnt have that function

**Comment by miaoski** [comment]
CoIMS on Zenfone 3 showed "App does not have Carrier Privileges" while the same SIM card on Mi 9 Pro 5G had carrier privileges.  I can ship a Zenfone 3 to you once TW recovers shipping to DE, if you want :)

**Comment by herlesupreeth** [comment]
oh is it. Did you try the latest version v0.9? (i published some fixes for Android 8.0 and 8.1 devices)

**Comment by miaoski** [comment]
I might have to wait for a while.  Currently my Zenfone 3 (Android 8) still sees v0.8 in Google Play.

**Comment by herlesupreeth** [comment]
Did the v0.9 of the app work on Zenfone 3?

**Comment by miaoski** [comment]
No.  It shows "App does not have Carrier Privileges".  I was using the SIM card that I had put in Mi 9 Pro, which worked with CoIMS 0.6.  However, I guess it's OK not to use CoIMS on Zenfone 3.  I have set the following properties in `adb shell` and VoLTE is enabled.
```
persist.dbg.ims_volte_enable=1
persist.dbg.volte_avail_ovr=1
persist.dbg.vt_avail_ovr=1
persist.dbg.wfc_avail_ovr=1
```

**Comment by herlesupreeth** [comment]
Then I would like to close this issue as I test on Oneplus 5t with Android 8.1 and it worked. Please feel free to re-open this issue if issue arises again.
